language: java
dist: trusty
addons:
  sonarcloud:
    organization: "tillerino-github"
    token:
      secure: "U7IZ4JYpiL9PuxEHeDCA09TkFmgPT93+lGg4fwm9fRna+O+we8lH++aMc7Ca/hwnHdDc2PJtasuMJ1yVje8iBJzJn6AF7eyx+48oa+LhYPUD98ccaLrCODoS4QIoPMRJMkTdJ+Z/lGcf8U/XgMnBYBrEohwOi6KD9K4TnddzRBw="

before_script:
  - wget https://raw.githubusercontent.com/sormuras/bach/e5e6492645f181df0a5a596b090a6b0bafda679f/install-jdk.sh
  - ./install-jdk.sh --feature 13

# we're not installing anything
install: true

script: >-
  if [ "${SONAR_SCANNER_HOME}" != "" ]; then
    mvn verify -Dmaven.javadoc.skip=true -B -V sonar:sonar
  else
    mvn verify -Dmaven.javadoc.skip=true -B -V
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
    - $HOME/.m2/repository
    - '$HOME/.sonar/cache'